name: Build and Release DEB Packages

on:
  push:
    tags:
      - "v*.*.*" # Activa este flujo al hacer push de un tag de versión

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up build environment
      run: sudo apt update && sudo apt install -y build-essential devscripts dh-make

    - name: Build DEB package
      run: |
        PACKAGE_NAME="nsniffer"
        VERSION="${{ github.ref_name }}" # Usa el tag como versión
        ARCHITECTURE="${{ matrix.architecture }}"
        INSTALL_PATH="/usr/local/bin"
        DEPENDENCIES="bash, tshark, arp-scan, dsniff"

        # Crear estructura del paquete
        mkdir -p $PACKAGE_NAME/DEBIAN
        mkdir -p $PACKAGE_NAME/$INSTALL_PATH

        # Crear archivo de control
        cat << EOF > $PACKAGE_NAME/DEBIAN/control
        Package: $PACKAGE_NAME
        Version: $VERSION
        Architecture: $ARCHITECTURE
        Maintainer: vorosdev@gmail.com
        Description: Simple tool for capturing and analyzing network packets
        Depends: $DEPENDENCIES
        EOF

        # Copiar el script principal al paquete
        cp ./nsniffer.sh $PACKAGE_NAME/$INSTALL_PATH/nsniffer
        chmod +x $PACKAGE_NAME/$INSTALL_PATH/nsniffer

        # Crear script postinst
        cat << 'EOF' > $PACKAGE_NAME/DEBIAN/postinst
        #!/bin/bash
        chmod +x /usr/local/bin/nsniffer
        EOF
        chmod +x $PACKAGE_NAME/DEBIAN/postinst

        # Generar el paquete .deb
        dpkg-deb --build $PACKAGE_NAME
        mv $PACKAGE_NAME.deb ${PACKAGE_NAME}_${VERSION}_${ARCHITECTURE}.deb

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          nsniffer_${{ github.ref_name }}_amd64.deb
          nsniffer_${{ github.ref_name }}_arm64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
